# Generated by Django 5.0.6 on 2024-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Subtitle', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='images')),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
