# Generated by Django 5.0.6 on 2024-07-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_blog_delete_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
